import {
  Baby,
  Bike,
  Bus,
  Car,
  Circle,
  Coffee,
  Dog,
  Dumbbell,
  Fuel,
  Gift,
  GraduationCap,
  HeartPulse,
  Home,
  Plane,
  Popcorn,
  Shirt,
  ShoppingCart,
  Smartphone,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export const ICONS_BY_NAME: Record<string, LucideIcon> = {
  'shopping-cart': ShoppingCart,
  zap: Zap,
  bike: Bike,
  coffee: Coffee,
  bus: Bus,
  'heart-pulse': HeartPulse,
  'graduation-cap': GraduationCap,
  home: Home,
  popcorn: Popcorn,
  circle: Circle,
  car: Car,
  fuel: Fuel,
  shirt: Shirt,
  baby: Baby,
  dog: Dog,
  gift: Gift,
  plane: Plane,
  smartphone: Smartphone,
  dumbbell: Dumbbell,
  wrench: Wrench,
}

export const ALLOWED_ICON_NAMES = Object.keys(ICONS_BY_NAME)

export const ICON_LABELS: Record<string, string> = {
  'shopping-cart': 'Carrito',
  zap: 'Rayo',
  bike: 'Bicicleta',
  coffee: 'Café',
  bus: 'Colectivo',
  'heart-pulse': 'Salud',
  'graduation-cap': 'Educación',
  home: 'Hogar',
  popcorn: 'Entretenimiento',
  circle: 'Otro',
  car: 'Auto',
  fuel: 'Combustible',
  shirt: 'Ropa',
  baby: 'Bebé',
  dog: 'Perro',
  gift: 'Regalo',
  plane: 'Avión',
  smartphone: 'Celular',
  dumbbell: 'Gimnasio',
  wrench: 'Herramientas',
}
